# Generated by Django 6.0.7 on 2026-07-23 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, unique=True, verbose_name='Nomi')),
                ('bino', models.CharField(blank=True, max_length=100, verbose_name='Bino')),
                ('xona', models.CharField(blank=True, max_length=50, verbose_name='Xona')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='F.I.Sh.')),
                ('lavozimi', models.CharField(blank=True, max_length=150, verbose_name='Lavozimi')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xodimlar', to='devices.bolim', verbose_name="Bo'lim")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi (login)')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='Qurilma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventar_raqami', models.CharField(max_length=50, unique=True, verbose_name='Inventar raqami')),
                ('turi', models.CharField(choices=[('kompyuter', 'Kompyuter'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('mfu', 'MFU'), ('proyektor', 'Proyektor'), ('skaner', 'Skaner'), ('ups', 'UPS'), ('boshqa', 'Boshqa')], max_length=20, verbose_name='Turi')),
                ('modeli', models.CharField(blank=True, max_length=200, verbose_name='Modeli')),
                ('seriya_raqami', models.CharField(blank=True, max_length=100, verbose_name='Seriya raqami')),
                ('holati', models.CharField(choices=[('ishlamoqda', 'Ishlamoqda'), ('tamirda', "Ta'mirda"), ('yaroqsiz', 'Yaroqsiz')], default='ishlamoqda', max_length=20, verbose_name='Holati')),
                ('olingan_sana', models.DateField(blank=True, null=True, verbose_name='Olingan sana')),
                ('qr_kod', models.ImageField(blank=True, upload_to='qr_kodlar/', verbose_name='QR-kod')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qurilmalar', to='devices.bolim', verbose_name="Bo'lim")),
                ('xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qurilmalar', to='devices.xodim', verbose_name='Biriktirilgan xodim')),
            ],
            options={
                'verbose_name': 'Qurilma',
                'verbose_name_plural': 'Qurilmalar',
                'ordering': ['inventar_raqami'],
            },
        ),
    ]
