# Generated by Django 6.0.7 on 2026-07-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qurilma',
            name='qr_kod',
        ),
    ]
