# Generated by Django 6.0.7 on 2026-07-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmalTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amal', models.CharField(choices=[('kirish', 'Tizimga kirdi'), ('chiqish', 'Tizimdan chiqdi'), ('kirish_xato', 'Kirishda xato'), ('parol', "Parolni o'zgartirdi"), ('yaratish', 'Yaratdi'), ('tahrirlash', 'Tahrirladi'), ('ochirish', "O'chirdi"), ('holat', "Holatni o'zgartirdi"), ('tasdiqlash', 'Tasdiqladi'), ('rad', 'Rad etdi'), ('ruxsatsiz', 'Ruxsatsiz urinish')], max_length=20, verbose_name='Amal')),
                ('obyekt', models.CharField(blank=True, max_length=200, verbose_name='Obyekt')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amallari', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Amal tarixi',
                'verbose_name_plural': 'Amallar tarixi',
                'ordering': ['-sana'],
                'indexes': [models.Index(fields=['-sana'], name='accounts_am_sana_3dcb2e_idx')],
            },
        ),
    ]
