# Generated by Django 6.0.7 on 2026-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_amaltarixi'),
    ]

    operations = [
        migrations.AddField(
            model_name='usta',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
